##Dataset 2 — Steel Industry Energy Consumption (Mafe)

In [21]:
import pandas as pd

Fonte: https://archive.ics.uci.edu/dataset/851/steel+industry+energy+consumption

Situação

A equipe de gestão de energia de uma indústria siderúrgica deseja localizar situações de consumo elevado e verificar se esses períodos coincidem com condições de carga elevada ou valores menos favoráveis de fator de potência.

In [22]:
df2 = pd.read_csv('/content/EX2_Steel_industry_data.csv')

##Carregue a amostra e renomeie Usage_kWh para Consumo_kWh, simplificando também os nomes dos atributos de fator de potência.

In [23]:
df2.rename(columns={'Usage_kWh': 'Consumo_kWh',
            'Lagging_Current_Power_Factor': 'Fator_corrente_atrasada',
            'Leading_Current_Power_Factor': 'Fator_Potencia',
            'Lagging_Current_Reactive.Power_kVarh': 'Potencia_Reativa_atrasada',
            'Leading_Current_Reactive_Power_kVarh': 'Potencia_Reativa',
            'WeekStatus': 'Status_Reativa',
            'Day_of_week': 'Dia_Semana'
            }, inplace=True)

##Apresente uma inspeção inicial com head(), shape, info() e describe().

In [24]:
df2.head()

,date,Consumo_kWh,Fator_corrente_atrasada,Fator_Potencia,Potencia_Reativa_atrasada,Potencia_Reativa,Status_Reativa,Dia_Semana,Load_Type
0,29/04/2018 07:15,2.88,60.20,100.00,3.82,0.0,Weekend,Sunday,Light_Load
1,04/10/2018 12:00,60.77,78.46,100.00,48.02,0.0,Weekday,Thursday,Maximum_Load
2,26/01/2018 11:30,120.42,89.61,100.00,59.65,0.0,Weekday,Friday,Maximum_Load
3,02/06/2018 14:30,3.13,100.00,18.53,0.00,16.6,Weekend,Saturday,Light_Load
4,07/12/2018 15:00,58.86,94.19,100.00,20.99,0.0,Weekday,Friday,Medium_Load

In [25]:
df2.shape

(7008, 9)

In [26]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7008 entries, 0 to 7007
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   date                       7008 non-null   object
 1   Consumo_kWh                7008 non-null   float64
 2   Fator_corrente_atrasada    7008 non-null   float64
 3   Fator_Potencia             7008 non-null   float64
 4   Potencia_Reativa_atrasada  7008 non-null   float64
 5   Potencia_Reativa           7008 non-null   float64
 6   Status_Reativa             7008 non-null   object
 7   Dia_Semana                 7008 non-null   object
 8   Load_Type                  7008 non-null   object
dtypes: float64(5), object(4)
memory usage: 492.9+ KB

In [27]:
df2.describe()

,Consumo_kWh,Fator_corrente_atrasada,Fator_Potencia,Potencia_Reativa_atrasada,Potencia_Reativa
count,7008.000000,7008.000000,7008.000000,7008.000000,7008.000000
mean,27.790164,80.672277,84.491448,13.206839,3.803711
std,33.717719,18.869855,30.314798,16.444246,7.356412
min,2.450000,37.870000,12.710000,0.000000,0.000000
25%,3.200000,63.602500,99.710000,2.380000,0.000000
50%,4.570000,87.990000,100.000000,5.040000,0.000000
75%,52.107500,98.842500,100.000000,22.977500,1.857500
max,153.140000,100.000000,100.000000,87.700000,27.650000

##Determine o maior consumo registrado e calcule um limiar de 75% do consumo máximo.

In [28]:
df2['Consumo_kWh'].max()

153.14

In [29]:
PMAX = df2['Consumo_kWh'].max()
P75 = 0.75 * PMAX
limiar_max = df2[df2['Consumo_kWh'] > P75]
limiar_max

,date,Consumo_kWh,Fator_corrente_atrasada,Fator_Potencia,Potencia_Reativa_atrasada,Potencia_Reativa,Status_Reativa,Dia_Semana,Load_Type
2,26/01/2018 11:30,120.42,89.61,100.0,59.65,0.0,Weekday,Friday,Maximum_Load
62,08/02/2018 14:30,118.22,90.95,100.0,54.04,0.0,Weekday,Thursday,Medium_Load
100,29/01/2018 16:45,129.13,94.07,100.0,46.58,0.0,Weekday,Monday,Medium_Load
108,29/01/2018 14:00,117.07,92.95,100.0,46.44,0.0,Weekday,Monday,Medium_Load
159,22/11/2018 10:15,139.57,92.13,100.0,58.90,0.0,Weekday,Thursday,Maximum_Load
...,...,...,...,...,...,...,...,...,...
6857,22/11/2018 09:00,124.49,92.34,100.0,51.73,0.0,Weekday,Thursday,Light_Load
6865,02/05/2018 15:30,117.54,93.94,100.0,42.91,0.0,Weekday,Wednesday,Maximum_Load
6932,10/08/2018 13:30,123.80,89.34,100.0,62.24,0.0,Weekday,Friday,Maximum_Load
6933,21/02/2018 16:45,115.81,92.21,100.0,48.60,0.0,Weekday,Wednesday,Medium_Load
7005,01/02/2018 12:00,145.51,87.13,100.0,81.94,0.0,Weekday,Thursday,Maximum_Load

In [30]:
limiar_max.shape

(129, 9)

##Crie um DataFrame contendo os registros acima desse limiar e calcule a quantidade e o percentual de registros.

In [31]:
df2_1 = df2[df2['Consumo_kWh'] > P75]
df2.head()

,date,Consumo_kWh,Fator_corrente_atrasada,Fator_Potencia,Potencia_Reativa_atrasada,Potencia_Reativa,Status_Reativa,Dia_Semana,Load_Type
0,29/04/2018 07:15,2.88,60.20,100.00,3.82,0.0,Weekend,Sunday,Light_Load
1,04/10/2018 12:00,60.77,78.46,100.00,48.02,0.0,Weekday,Thursday,Maximum_Load
2,26/01/2018 11:30,120.42,89.61,100.00,59.65,0.0,Weekday,Friday,Maximum_Load
3,02/06/2018 14:30,3.13,100.00,18.53,0.00,16.6,Weekend,Saturday,Light_Load
4,07/12/2018 15:00,58.86,94.19,100.00,20.99,0.0,Weekday,Friday,Medium_Load

In [32]:
qtd_selecionados = len(df2_1)
qtd_total = len(df2)

df2_1_percentual = (qtd_selecionados / qtd_total) * 100

print(f'Registros selecionados: {qtd_selecionados} de {qtd_total}.')
print(f'O percentual da amostra representa {df2_1_percentual:.2f}%.')

Registros selecionados: 129 de 7008.
O percentual da amostra representa 1.84%.

##Verifique quantos registros desse DataFrame pertencem à categoria Maximum Load.

In [33]:
qtd_maximum_load = df2_1[df2_1['Load_Type'] == 'Maximum_Load'].shape[0]

print(f'Registros da categoria Maximum_Load: {qtd_maximum_load} de {len(df2_1)} registros de consumo elevado.')

Registros da categoria Maximum_Load: 62 de 129 registros de consumo elevado.

##Escolha um dos atributos de fator de potência, observe seus valores e defina um limite coerente para representar valores mais baixos.

In [34]:
df2['Fator_Potencia'].describe()
limite_fp = 50

##Crie um novo DataFrame contendo simultaneamente consumo elevado e fator de potência abaixo do limite escolhido.

In [35]:
df2_2 = df2[(df2['Consumo_kWh'] > P75) & (df2['Fator_Potencia'] < limite_fp)]

qtd_selecionados = len(df2_2)
qtd_total = len(df2)
df2_2_percentual = (qtd_selecionados / qtd_total) * 100

print(f'Registros selecionados: {qtd_selecionados} de {qtd_total}.')
print(f'O percentual da amostra representa {df2_2_percentual:.2f}%.')

Registros selecionados: 0 de 7008.
O percentual da amostra representa 0.00%.

##Explique por que esse segundo conjunto de registros pode merecer maior atenção da equipe de energia.

Esse cruzamento (consumo alto + fator de potência baixo) seria o cenário mais crítico pra equipe de energia, pois indica ineficiência no uso da energia e pode gerar multas na conta. Porém, nesta amostra o resultado deu 0 registros: quando o consumo está no pico, o Fator_Potencia (Leading) fica sempre saturado em 100, ou seja, esse atributo específico não é o responsável por ineficiência nos momentos de consumo elevado.