###Dataset 6 —  Individual Household Electric Power Consumption (UCI) (Bia)

In [ ]:
import pandas as pd

Fonte: https://archive.ics.uci.edu/dataset/235/individual+household+electric+power+consumption

Situação

Uma residência possui monitoramento elétrico detalhado e deseja identificar episódios de demanda elevada que também apresentem corrente acima do comportamento médio. O dataset é o mesmo utilizado como referência em aula, mas o critério de análise será diferente.

In [100]:
df6 = pd.read_csv("SAMPLE_DATASET6_10.csv", skiprows=[1, 2])

1. Carregue a nova amostra e organize os atributos utilizando nomes mais simples.

In [101]:
df6.head()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,0.584,0.148,245.90,2.4,0,0,0
1,1.492,0.328,239.96,6.2,0,2,18
2,1.020,0.182,239.71,4.4,0,0,11
3,0.718,0.146,243.44,3.0,0,0,0
4,1.066,0.290,242.02,4.6,0,2,11

In [104]:
df6 = df6.rename(columns={
    "Global_active_power": "active_power",
    "Global_reactive_power": "reactive_power",
    "Voltage": "voltage",
    "Global_intensity": "intensity",
    "Sub_metering_1": "sub_metering_1",
    "Sub_metering_2": "sub_metering_2",
    "Sub_metering_3": "sub_metering_3"
})

df6.columns

Index(['active_power', 'reactive_power', 'voltage', 'intensity',
       'sub_metering_1', 'sub_metering_2', 'sub_metering_3'],
      dtype='object')

2. Determine o valor máximo de potência ativa.

In [105]:
max_active_power = df6["active_power"].max()

print("Potência ativa máxima:", max_active_power)

Potência ativa máxima: 10.29

3. Calcule 75% do valor máximo e crie um DataFrame contendo registros acima desse limite.

In [114]:
limite_75 = max_active_power * 0.75

print(f"Limite de 75% da potência máxima: {limite_75:.2f}")

Limite de 75% da potência máxima: 7.72

In [115]:
df6_acima_75 = df6[df6["active_power"] > limite_75]

df6_acima_75.head()

,active_power,reactive_power,voltage,intensity,sub_metering_1,sub_metering_2,sub_metering_3
994,10.29,0.302,230.9,44.6,35,66,17
2268,7.78,0.170,235.0,33.0,36,35,17

4. Calcule a quantidade e o percentual de registros selecionados.

In [116]:
print("Quantidade de registros:", len(df6_acima_75))

Quantidade de registros: 2

In [120]:
quantidade_75 = len(df6_acima_75)
percentual_75 = (quantidade_75 / len(df6)) * 100

print("Quantidade de registros acima de 75%:", quantidade_75)
print(f"Percentual de registros acima de 75%: {percentual_75:.2f}%")

Quantidade de registros acima de 75%: 2
Percentual de registros acima de 75%: 0.01%

5. Calcule a corrente média da amostra.

In [123]:
corrente_media = df6["intensity"].mean()

print(f"Corrente média da amostra: {corrente_media:.2f}")

Corrente média da amostra: 4.64

6. Crie um segundo DataFrame contendo simultaneamente potência ativa acima de 75% do máximo e corrente acima da média.

In [126]:
df6_alto_consumo = df6[
    (df6["active_power"] > limite_75) &
    (df6["intensity"] > corrente_media)
]

df6_alto_consumo

,active_power,reactive_power,voltage,intensity,sub_metering_1,sub_metering_2,sub_metering_3
994,10.29,0.302,230.9,44.6,35,66,17
2268,7.78,0.170,235.0,33.0,36,35,17

In [128]:
quantidade_alto_consumo = len(df6_alto_consumo)
percentual_alto_consumo = (quantidade_alto_consumo / len(df6)) * 100

print("Quantidade de registros:", quantidade_alto_consumo)
print(f"Percentual de registros: {percentual_alto_consumo:.2f} %")

Quantidade de registros: 2
Percentual de registros: 0.01 %

7. Compare os dois conjuntos e explique o efeito da inclusão da corrente como segunda condição.

**Compare os dois conjuntos e explique o efeito da inclusão da corrente como segunda condição.**

Comparação dos conjuntos:
A primeira condição selecionou 2 registros, correspondentes a 0,0122% da amostra, com potência ativa superior a 75% do valor máximo observado. Ao adicionar a corrente como segunda condição, considerando apenas registros com corrente acima da média de 4,641 A, os mesmos 2 registros permaneceram selecionados. Portanto, neste caso, a inclusão da corrente não reduziu a quantidade de registros identificados, pois os dois episódios de maior demanda também apresentaram corrente significativamente superior à média. Isso indica que, para esta amostra, os episódios de potência elevada estão associados a um comportamento de corrente elevada.

Conclusão:
A utilização conjunta da potência ativa e da corrente permite identificar episódios que apresentam simultaneamente alta demanda elétrica e corrente acima do comportamento médio. Embora, nesta amostra, a segunda condição não tenha alterado a quantidade de registros selecionados, ela torna o critério de identificação mais específico, pois exige que as duas características ocorram simultaneamente.