###Dataset 3 — Power Consumption of Tetouan City (Ana ju)

In [ ]:
import pandas as pd

Fonte: https://archive.ics.uci.edu/dataset/849/power+consumption+of+tetouan+city

Situação

Uma equipe responsável pelo planejamento da distribuição de energia em Tétouan deseja identificar qual das três zonas apresenta o maior pico de consumo e observar as condições ambientais registradas nos momentos de maior demanda.

In [91]:
dados = pd.read_csv('OFTetuan_City_power_consumption_-_amostra_15__CERTO.csv')

1. Renomeie as três variáveis de consumo para Consumo_Zona_1, Consumo_Zona_2 e
Consumo_Zona_3.

In [92]:
dados = dados.rename({'Zone 1 Power Consumption': 'Consumo_Zona_1',
                      'Zone 2  Power Consumption': 'Consumo_Zona_2',
                      'Zone 3  Power Consumption': 'Consumo_Zona_3'},
                     axis=1)

# Convert the power consumption columns to numeric, coercing errors
power_cols = ['Consumo_Zona_1', 'Consumo_Zona_2', 'Consumo_Zona_3']
for col in power_cols:
    dados[col] = pd.to_numeric(dados[col], errors='coerce')

In [93]:
dados.columns

Index(['DateTime', 'Temperature', 'Humidity', 'Wind Speed', 'Consumo_Zona_1',
       'Consumo_Zona_2', 'Consumo_Zona_3'],
      dtype='object')

2. Determine o consumo máximo registrado em cada uma das três zonas.

In [94]:
max_consumo = dados[['Consumo_Zona_1', 'Consumo_Zona_2', 'Consumo_Zona_3']].max()
max_consumo

Consumo_Zona_1    51571.49834
Consumo_Zona_2    36437.20000
Consumo_Zona_3    47441.70000
dtype: float64

3. Identifique qual zona apresenta o maior pico de consumo na amostra.

In [95]:
zona_maior_pico = max_consumo.idxmax()
print(f"A zona com o maior pico de consumo é: {zona_maior_pico}")

A zona com o maior pico de consumo é: Consumo_Zona_1

  4. Para a zona identificada, calcule 70% do valor máximo e crie um DataFrame com os registros acima desse limiar.

In [96]:
max_consumo_zona_maior_pico = max_consumo[zona_maior_pico]
limiar_70_pico = 0.70 * max_consumo_zona_maior_pico

df_alta_consumo = dados[dados[zona_maior_pico] > limiar_70_pico].copy()

print(f"Valor máximo de consumo para {zona_maior_pico}: {max_consumo_zona_maior_pico:.2f}")
print(f"70% do valor máximo de consumo para {zona_maior_pico}: {limiar_70_pico:.2f}")
print(f"DataFrame com registros acima do limiar de 70% (df_alta_consumo):")
display(df_alta_consumo.head())
print(f"Número de registros em df_alta_consumo: {len(df_alta_consumo)}")

Valor máximo de consumo para Consumo_Zona_1: 51571.50
70% do valor máximo de consumo para Consumo_Zona_1: 36100.05
DataFrame com registros acima do limiar de 70% (df_alta_consumo):

,DateTime,Temperature,Humidity,Wind Speed,Consumo_Zona_1,Consumo_Zona_2,Consumo_Zona_3
3,3/19/2017 20:20,12.42,72.30,0.081,42476.93617,23634.1,25089.7
8,12/10/2017 17:50,14.66,65.92,0.075,37286.69202,30716.2,15834.8
12,6/5/2017 23:30,21.03,86.50,0.068,40993.90728,25383.4,24960.0
14,8/23/2017 17:50,27.06,47.58,4.905,37475.16093,24276.2,25140.6
19,6/22/2017 2:40,19.20,65.81,4.924,40676.02649,24754.7,25095.9

Número de registros em df_alta_consumo: 2388

5. Conte os registros e calcule o percentual que eles representam.

In [97]:
num_registros_alta_consumo = len(df_alta_consumo)
total_registros_originais = len(dados)

percentual_alta_consumo = (num_registros_alta_consumo / total_registros_originais) * 100

print(f"Número de registros de alta consumo: {num_registros_alta_consumo}")
print(f"Total de registros no dataset original: {total_registros_originais}")
print(f"Percentual de registros de alta consumo: {percentual_alta_consumo:.2f}%")

Número de registros de alta consumo: 2388
Total de registros no dataset original: 7863
Percentual de registros de alta consumo: 30.37%

6. Calcule a temperatura média e crie um segundo DataFrame contendo consumo acima do limiar e temperatura acima da média.

In [98]:
media_temperatura = dados['Temperature'].mean()

df_alta_consumo_temp_alta = df_alta_consumo[df_alta_consumo['Temperature'] > media_temperatura].copy()

print(f"Temperatura média no dataset original: {media_temperatura:.2f}°C")
print(f"DataFrame com registros de alta consumo e temperatura acima da média (df_alta_consumo_temp_alta):")
display(df_alta_consumo_temp_alta.head())
print(f"Número de registros em df_alta_consumo_temp_alta: {len(df_alta_consumo_temp_alta)}")

Temperatura média no dataset original: 18.79°C
DataFrame com registros de alta consumo e temperatura acima da média (df_alta_consumo_temp_alta):

,DateTime,Temperature,Humidity,Wind Speed,Consumo_Zona_1,Consumo_Zona_2,Consumo_Zona_3
12,6/5/2017 23:30,21.03,86.50,0.068,40993.90728,25383.4,24960.0
14,8/23/2017 17:50,27.06,47.58,4.905,37475.16093,24276.2,25140.6
19,6/22/2017 2:40,19.20,65.81,4.924,40676.02649,24754.7,25095.9
21,8/23/2017 13:50,27.11,43.35,4.906,40256.07103,27416.3,25453.5
25,7/12/2017 9:50,26.92,70.20,4.909,36511.89369,25906.3,25654.9

Número de registros em df_alta_consumo_temp_alta: 1597

7. Compare os dois conjuntos e explique o que ocorreu com a quantidade de registros após a inclusão da condição ambiental.

In [99]:
num_registros_alta_consumo_temp_alta = len(df_alta_consumo_temp_alta)

percentual_alta_consumo_temp_alta = (num_registros_alta_consumo_temp_alta / total_registros_originais) * 100

print(f"Número de registros em df_alta_consumo (apenas alta consumo): {num_registros_alta_consumo}")
print(f"Percentual de registros em df_alta_consumo: {percentual_alta_consumo:.2f}%")
print("\n")
print(f"Número de registros em df_alta_consumo_temp_alta (alta consumo E alta temperatura): {num_registros_alta_consumo_temp_alta}")
print(f"Percentual de registros em df_alta_consumo_temp_alta: {percentual_alta_consumo_temp_alta:.2f}%")

reducao_registros = num_registros_alta_consumo - num_registros_alta_consumo_temp_alta
percentual_reducao = (reducao_registros / num_registros_alta_consumo) * 100

print("\n")
print(f"Ao incluir a condição de temperatura acima da média, o número de registros reduziu em: {reducao_registros} ({-percentual_reducao:.2f}%) registros.")
print(f"Isso significa que {percentual_reducao:.2f}% dos registros de alta consumo ocorrem com temperatura igual ou abaixo da média.")

Número de registros em df_alta_consumo (apenas alta consumo): 2388
Percentual de registros em df_alta_consumo: 30.37%


Número de registros em df_alta_consumo_temp_alta (alta consumo E alta temperatura): 1597
Percentual de registros em df_alta_consumo_temp_alta: 20.31%


Ao incluir a condição de temperatura acima da média, o número de registros reduziu em: 791 (-33.12%) registros.
Isso significa que 33.12% dos registros de alta consumo ocorrem com temperatura igual ou abaixo da média.